### ISSUE TITLE
attachListener rendition #1

### ISSUE THREAD

**Issue by david-mark** [cinsoft/jessie#257]
Appears to have been extracted from the more complicated renditions. The bit that uses Function.prototype.call is an unneeded artifact in rendition #1.

**Comment by adamsilver** [comment]
@david-mark how can I remove `call` inside rendition1? It needs to call the function with the element as `this` - or is that you get that for free without calling? *goes to check*

**Comment by adamsilver** [comment]
Does this work for you @david-mark https://github.com/david-mark/jessie/pull/306
